[package]
name = "spotifydl-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
directories.workspace = true
iced.workspace = true
rfd = "0.15.4"
spotifydl-protocol = { path = "../spotifydl-protocol" }
spotifydl-service = { path = "../spotifydl-service" }
